version: 2

sources:
    - name: staging
      #For bigquery:
      database: mythic-plexus-375706

      # For postgres:
      # database: production

      schema: trips_data_all

      # loaded_at_field: record_loaded_at
      tables:
        - name: fhv_2019
        - name: green_tripdata
        - name: yellow_tripdata
         # freshness:
           # error_after: {count: 6, period: hour}
